// Cosmetic
// device
//employ
var Devices = {
    0: {
      name: "EpCare-Zenith",
      img: "EpCare-Zenith.png",
      pdf: "EpCare-Zenith",
      type: "",
      class: "device",
    },
    1: {
      name: "Aleste Combi",
      img: "AlesteCombi.png",
      pdf: "AlesteCombi",
      type: "",
      class: "device",
    },
    2: {
      name: "Again Deka",
      img: "AgainDeka.png",
      pdf: "AgainDeka",
      type: "",
      class: "device",
    },
    3: {
      name: "Q10",
      img: "Q10.png",
      pdf: "Q10",
      type: "",
      class: "device",
    },
    4: {
      name: "Cryo-zet",
      img: "Cryo-zet.png",
      pdf: "Cryo-zet",
      type: "",
      class: "device",
    },
    5: {
      name: "Somke evacuator(DS-2000EN)",
      img: "Somkeevacuator.png",
      pdf: "Somkeevacuator",
      type: "",
      class: "device",
    },
    6: {
      name: "Smaxel co2 laser",
      img: "Smaxelco2laser.png",
      pdf: "Smaxelco2laser",
      type: "",
      class: "device",
    },
    7: {
      name: "Erica",
      img: "Erica.png",
      pdf: "Erica",
      type: "",
      class: "device",
    },
    8: {
      name: "Hipro-V",
      img: "Hipro-V.png",
      pdf: "Hipro-V",
      type: "",
      class: "device",
    },
    9: {
      name: "Plasma bt",
      img: "Plasmabt.png",
      pdf: "Plasmabt",
      type: "",
      class: "device",
    },
    10: {
      name: "Endolift Lasemar1500",
      img: "Endolift.png",
      pdf: "Endolift",
      type: "",
      class: "device",
    },
    11: {
      name: "J-Plasma",
      img: "J-Plasma.png",
      pdf: "J-Plasma",
      type: "",
      class: "device",
    },
    12: {
      name: "Lipo Surg",
      img: "LipoSurg.png",
      pdf: "LipoSurg",
      type: "",
      class: "device",
    },
    13: {
      name: "Orchestra Cool",
      img: "OrchestraCool.png",
      pdf: "OrchestraCool",
      type: "",
      class: "device",
    },
    14: {
      name: "Ashley",
      img: "",
      pdf: "Ashley.png",
      type: "Ashley",
      class: "device",
    },
    15: {
      name: "Einxelx2",
      img: "Einxelx2.png",
      pdf: "Einxelx2",
      type: "",
      class: "device",
    },
    16: {
      name: "HRZ-6000 Diode laser",
      img: "HRZ-6000Diodelaser.png",
      pdf: "HRZ-6000Diodelaser",
      type: "",
      class: "device",
    },
    17: {
      name: "Hydra facial",
      img: "Hydrafacial.png",
      pdf: "Hydrafacial",
      type: "",
      class: "device",
    },
    18: {
      name: "Med-Jet",
      img: "Med-Jet.png",
      pdf: "Med-Jet",
      type: "",
      class: "device",
    },
  },
  Cosmetics = {
    0: {
      name: "Botulax",
      img: "botulax.png",
      pdf: "botulax",
      type: "",
      class: "cosmetic",
    },
    1: {
      name: "Meditoxin",
      img: "medtoxin.png",
      pdf: "medtoxin",
      type: "",
      class: "cosmetic",
    },
    2: {
      name: "Re N Tox",
      img: "rentox.png",
      pdf: "rentox",
      type: "",
      class: "cosmetic",
    },
    3: {
      name: "Angela SUB-Q",
      img: "sub-q.png",
      pdf: "sub-q",
      type: "",
      class: "cosmetic",
    },
    4: {
      name: "Angela FINE",
      img: "fine.png",
      pdf: "fine",
      type: "",
      class: "cosmetic",
    },
    5: {
      name: "Angela DEEP",
      img: "deep.png",
      pdf: "deep",
      type: "",
      class: "cosmetic",
    },
    6: {
      name: "Anti Filler",
      img: "Anti-Filler.png",
      pdf: "Anti-Filler",
      type: "",
      class: "cosmetic",
    },
    7: {
      name: "American PRP Tube",
      img: "PRP.png",
      pdf: "PRP",
      type: "",
      class: "cosmetic",
    },
    8: {
      name: "PRP Liquid Activator",
      img: "PRP-Liquid-Activator.png",
      pdf: "PRP-Liquid-Activator",
      type: "",
      class: "cosmetic",
    },
    9: {
      name: "PRP Physical Activator",
      img: "PRP-Physical-Activator.png",
      pdf: "PRP-Physical-Activator",
      type: "",
      class: "cosmetic",
    },
    10: {
      name: "Derma Pen",
      img: "derma-pen.png",
      pdf: "derma-pen",
      type: "",
      class: "cosmetic",
    },
    11: {
      name: "Neo Thread Series",
      img: "neo-thread.png",
      pdf: "neo-thread",
      type: "",
      class: "cosmetic",
    },
    12: {
      name: "Woods Lamp",
      img: "Woods-Lamp.png",
      pdf: "Woods-Lamp",
      type: "",
      class: "cosmetic",
    },
    13: {
      name: "Lead Head Light",
      img: "Lead-Head-Light.png",
      pdf: "Lead-Head-Light",
      type: "",
      class: "cosmetic",
    },
    14: {
      name: "Meso Gun",
      img: "meso-gun.png",
      pdf: "meso-gun",
      type: "",
      class: "cosmetic",
    },
    15: {
      name: "Microdermabrasion",
      img: "Microdermabrasion.png",
      pdf: "Microdermabrasion",
      type: "",
      class: "cosmetic",
    },
    16: {
      name: "Derma Roller",
      img: "Derma-Roller.png",
      pdf: "Derma-Roller",
      type: "",
      class: "cosmetic",
    },
    17: {
      name: "Magnavision",
      img: "Magnavision.png",
      pdf: "Magnavision",
      type: "",
      class: "cosmetic",
    },
    18: {
      name: "Skin Biopsy Puncher",
      img: "Skin-Biopsy-Puncher.png",
      pdf: "Skin-Biopsy-Puncher",
      type: "",
      class: "cosmetic",
    },
    19: {
      name: "Spot RemovalPen",
      img: "Spot-Removal-Pen.png",
      pdf: "Spot-Removal-Pen",
      type: "",
      class: "cosmetic",
    },
    20: {
      name: "Thermo Cautery",
      img: "Thermo-Cautery.png",
      pdf: "Thermo-Cautery",
      type: "",
      class: "cosmetic",
    },
    21: {
      name: "Electro Cautery",
      img: "Electro-Cautery.png",
      pdf: "Electro-Cautery",
      type: "",
      class: "cosmetic",
    },
    22: {
      name: "RF Cautery",
      img: "RF-Cautery.png",
      pdf: "RF-Cautery",
      type: "",
      class: "cosmetic",
    },
    23: {
      name: "Centrifuge",
      img: "Centrifuge.png",
      pdf: "Centrifuge",
      type: "",
      class: "cosmetic",
    },
    24: {
      name: "Derma Scoop",
      img: "Derma-Scoop.png",
      pdf: "Derma-Scoop",
      type: "",
      class: "cosmetic",
    },
    25: {
      name: "Hair Transplant instruments",
      img: "Hair-Transplant-Instruments.png",
      pdf: "Hair-Transplant-Instruments",
      type: "",
      class: "cosmetic",
    },
    26: {
      name: "Cannulas",
      img: "Cannulas.png",
      pdf: "Cannulas",
      type: "",
      class: "cosmetic",
    },
    27: {
      name: "Surgery Instruments",
      img: "Surgery-Instruments.png",
      pdf: "Surgery-Instruments",
      type: "",
      class: "cosmetic",
    },
    28: {
      name: "Cosmo Chair",
      img: "manual-dermatology-chair.png",
      pdf: "manual-dermatology-chair",
      type: "",
      class: "cosmetic",
    },
    29: {
      name: "Cosmo Chair",
      img: "manual-dermatology-chair-02.png",
      pdf: "manual-dermatology-chair",
      type: "",
      class: "cosmetic",
    },
  },
  employes = {
    owner: {
      0: {
        name: "",
        position: "",
        img: "",
      },
      1: {
        name: "Mr. Mohammed Ali ",
        position: "Public Relationship(Owner)",
        img: "ma",
      },
    },
    sales: {
      0: {
        name: "",
        position: "",
        img: "",
      },
    },
    eng: {
      0: {
        name: "",
        position: "",
        img: "",
      },
    },
    services: {
      0: {
        name: "",
        position: "",
        img: "",
      },
    },
    others: {
      0: {
        name: "",
        position: "",
        img: "",
      },
    },
    
  };
